// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPiTest.Context;

#nullable disable

namespace MinimalAPiTest.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20220902054748_EstadoTarea")]
    partial class EstadoTarea
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MinimalAPiTest.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaID = 100,
                            Descripcion = "algo",
                            Nombre = "Personal"
                        },
                        new
                        {
                            CategoriaID = 110,
                            Descripcion = "algo mas",
                            Nombre = "Trabajo"
                        },
                        new
                        {
                            CategoriaID = 200,
                            Descripcion = "estudio",
                            Nombre = "Facultad"
                        });
                });

            modelBuilder.Entity("MinimalAPiTest.Models.Tarea", b =>
                {
                    b.Property<int>("TareaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaID"), 1L, 1);

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoTarea")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<bool>("Procastinable")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TareaID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaID = 1151,
                            CategoriaID = 100,
                            Estado = false,
                            EstadoTarea = 0,
                            FechaCreacion = new DateTime(2022, 9, 2, 2, 47, 48, 187, DateTimeKind.Local).AddTicks(3848),
                            PrioridadTarea = 1,
                            Procastinable = false,
                            Titulo = "Pago de servidios publico"
                        },
                        new
                        {
                            TareaID = 2252,
                            CategoriaID = 200,
                            Estado = false,
                            EstadoTarea = 0,
                            FechaCreacion = new DateTime(2022, 9, 2, 2, 47, 48, 187, DateTimeKind.Local).AddTicks(3858),
                            PrioridadTarea = 0,
                            Procastinable = false,
                            Titulo = "Estudiar para parcial"
                        });
                });

            modelBuilder.Entity("MinimalAPiTest.Models.Tarea", b =>
                {
                    b.HasOne("MinimalAPiTest.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MinimalAPiTest.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
